config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'

  authenticated :users do
    root 'notes#index', as: 'authenticated_root'
  end

  resources :notes

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :find_note, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

	def index
		@notes = Note.where(user_id: current_user)
	end

	def show
		
	end

	def new
		@note = current_user.notes.build
	end

	def create
		@note = current_user.notes.build(note_params)

		if @note.save
			redirect_to @note
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @note.update(note_params)
			redirect_to @note
		else
			render 'edit'
		end
	end

	def destroy
		@note.destroy
		redirect_to notes_path
	end

	private

	def find_note
		@note = Note.find(params[:id])
	end

	def note_params
		params.require(:note).permit(:title, :content)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Note | On the go Notebook Application
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%header
		
		.header_inner
			= link_to image_tag('personalLogo.png'), notes_path, id:"personalLogo"

			%nav
				- if user_signed_in?
					= link_to "New Note", new_note_path
					= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
					= link_to "Log In", new_user_session_path
					= link_to "Sign Up", new_user_registration_path
	%p.notice= notice
	%p.alert= alert

	= yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
	= f.input :title
	= f.input :content
	= f.button :submit

app/views/notes/edit.html.haml
.wrapper_with_padding
	%h1 Edit Note

	= render 'form'

	= link_to 'Cancel', note_path

app/views/notes/index.html.haml
.wrapper_with_padding
	#notes.clearfix
		- unless @notes.blank?
			- @notes.each do |note|
				%a{ href: (url_for [note])}
					.note
						%p.title= note.title
						%p.date= time_ago_in_words(note.created_at)
		- else
			%h2 Add a Note
			%p It appears you haven't created any notes yet... go ahead and create a new note.
			%button= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
.wrapper_with_padding
	%h1 Add A Note

	= render 'form'

app/views/notes/show.html.haml
.wrapper_with_padding
	#note_show
		%h1.title= @note.title
		%p= simple_format(@note.content)

		.buttons
			= link_to 'Edit', edit_note_path(@note), class: "button"
			= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button"

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 Funnote
		%p Notes on the go. Never forget your ideas again.

#quotation
	.circle
		%p Try sample
		%p click Log In
		%p then click Foxy logo!
	.wrapper
		%p.quote &ldquo;Imagination is more important than knowledge.&rdquo;
		%p.name - Albert Einstein -
		%br
		%p.quote &ldquo;To find yourself, think for yourself..&rdquo;
		%p.name - Socrates -
		%br
		%p.quote &ldquo;When you want something, all the universe conspires in helping you to achieve it..&rdquo;
		%p.name - Paulo Coelho -
		%br
		%p.quote &ldquo;You have to take risks. We will only understand the miracle of life fully when we allow the unexpected to happen..&rdquo;
		%p.name - Paulo Coelho -
		%br


%footer

	%p &copy; 2014 Franklin